# Generated by Django 5.2.4 on 2025-07-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=4)),
                (
                    "status",
                    models.CharField(
                        choices=[("SAVED", "Saved"), ("FAVORITE", "Favorite")],
                        max_length=10,
                    ),
                ),
                ("image_url", models.URLField()),
                ("link_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("title", "year")},
            },
        ),
    ]
