# Generated by Django 5.2.4 on 2025-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("SAVED", "Saved"), ("FAVORITE", "Favorite")], max_length=8
            ),
        ),
    ]
