# Generated by Django 5.2.4 on 2025-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="link_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.TextField(
                choices=[("SAVED", "Saved"), ("FAVORITE", "Favorite")]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.TextField(),
        ),
    ]
