# Generated by Django 5.2.4 on 2025-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_image_url_alter_movie_link_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("SAVED", "Saved"), ("FAVORITE", "Favorite")],
                default="SAVED",
                max_length=8,
            ),
        ),
    ]
