# Generated by Django 5.2.4 on 2025-07-30 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="URL to movie poster image", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="link_url",
            field=models.URLField(
                blank=True, help_text="URL to movie page on Letterboxd", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("SAVED", "Saved"), ("FAVORITE", "Favorite")],
                default="SAVED",
                help_text="SAVED or FAVORITE",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.TextField(
                help_text="Full movie title",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(
                help_text="Release year (YYYY)",
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
